version: "3.9"

services:
  api:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./api
    env_file:
      - ./config/envFiles/django/prod/.env
    command: ./docker-entrypoint-prod.sh
    volumes:
      - static-data:/usr/src/app/vol
    depends_on:
      - db

  db:
    restart: always
    image: postgres:13-alpine
    env_file:
      - ./config/envFiles/postgres/prod/.env
    ports:
      - "${SERVER_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_backups:/db_backups

volumes:
  pgdata:
