# Generated by Django 4.2.16 on 2024-09-05 18:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=2048, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('excerpt', models.CharField(blank=True, max_length=2048, null=True)),
                ('preview_photo', models.FileField(blank=True, null=True, upload_to='blogs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('preview_photo_from_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('slug', models.SlugField(blank=True, max_length=2048, unique=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('meta_description', models.CharField(default="Stay updated with ISWAD Tech's Blog. Discover insights, tips, and industry trends on MVP development, web app creation, branding, and more. Our expert articles provide valuable knowledge to help your business grow and succeed. Explore innovative ideas and solutions with ISWAD Tech today.", max_length=2048)),
                ('meta_keywords', models.CharField(default='Tech Blog, Industry Insights, Latest Tech Trends, AI Innovations, Software Development Tips, Tech News, Business Technology, Digital Transformation, Expert Opinions, Innovation Articles', max_length=2048)),
                ('page_title', models.CharField(default='Blog | ISWAD', max_length=2048)),
                ('img_alt', models.CharField(default='Blog ISWAD', max_length=2048)),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_writer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Blogs',
                'ordering': ('-created_at', 'title'),
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(default='', max_length=256)),
                ('last_name', models.CharField(default='', max_length=256)),
                ('email', models.CharField(default='', max_length=256)),
                ('subject', models.CharField(default='', max_length=256)),
                ('message', models.TextField(default='')),
            ],
            options={
                'verbose_name_plural': 'Contact Forms',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=2048, unique=True)),
                ('label_type', models.CharField(choices=[('TAG', 'TAG'), ('CATEGORY', 'CATEGORY')], max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Labels',
                'ordering': ('title', 'label_type'),
            },
        ),
        migrations.CreateModel(
            name='UploadedMedia',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_file', models.FileField(upload_to='uploaded_media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'mp4'])])),
            ],
            options={
                'verbose_name_plural': 'Uploaded Media',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='WebSubscriber',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Web Subscribers',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BlogLabel',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_label_blog', to='app.blog')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_label_label', to='app.label')),
            ],
            options={
                'verbose_name_plural': 'Blog Labels',
                'ordering': ('-created_at',),
            },
        ),
    ]
