# Generated by Django 4.2.16 on 2024-09-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='phone_number',
            field=models.CharField(default='', max_length=256),
        ),
    ]
