# Generated by Django 4.2.16 on 2024-09-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='preview_photo_from_url',
        ),
        migrations.AlterField(
            model_name='blog',
            name='preview_photo',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
