# Generated by Django 4.2.13 on 2024-07-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_blog_meta_description_blog_meta_keywords_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='page_alt',
            new_name='page_title',
        ),
        migrations.AddField(
            model_name='blog',
            name='img_alt',
            field=models.CharField(default='Blog ISWAD', max_length=2048),
        ),
    ]
