# Generated by Django 4.2.14 on 2024-08-01 20:06

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_page_alt_blog_page_title_blog_img_alt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=2048, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('excerpt', models.CharField(blank=True, max_length=2048, null=True)),
                ('preview_photo', models.FileField(blank=True, null=True, upload_to='courses/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('preview_photo_from_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('slug', models.SlugField(blank=True, max_length=2048, unique=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('meta_description', models.CharField(default='Explore comprehensive development courses at ISWAD Tech. Learn front-end and back-end development, programming essentials, API integration, and DevOps practices. Our expertly crafted courses provide hands-on experience and real-world projects, empowering you to build a robust portfolio and advance your tech career. Join ISWAD Tech and master the skills needed to excel in the ever-evolving tech industry.', max_length=2048)),
                ('meta_keywords', models.CharField(default='Development Courses, Front-end Development, Back-end Development, Programming Essentials, API Integration, DevOps Practices, Tech Skills, Real-world Projects, Tech Career Advancement, ISWAD Tech Courses', max_length=2048)),
                ('page_title', models.CharField(default='Learning | ISWAD', max_length=2048)),
                ('img_alt', models.CharField(default='Learning ISWAD', max_length=2048)),
                ('price', models.FloatField(default=0)),
                ('training_hours', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Courses',
                'ordering': ('-created_at', 'title'),
            },
        ),
    ]
